---
Name: kapostbridge
After:
    - "framework/*"
    - "cms/*"
---
SiteTree:
    extensions:
        - "KapostSiteTreeExtension"
    non_readonly_fields:
        - "URLSegment"
        - "ExtraMeta"
    make_safe_wysiwyg_fields:
        - "Content"
